### ISSUE TITLE
"Null check operator used on a null value" was thrown during a scheduler callback

### ISSUE THREAD

**Issue by willbryant** [muhammadtalhasultan/flutter-slide-to-act#8]
Getting this sometimes, I think when I have scrolled the container that contains the slide into view and then scroll it out, but I can't reproduce it consistently.

```
The following _CastError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      SlideActionState.initState.<anonymous closure> (package:slide_to_act/slide_to_act.dart:387:39)
#1      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#2      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#3      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#7      _invoke (dart:ui/hooks.dart:161:10)
```

Which comes from:

```
      final RenderBox containerBox =
          _containerKey.currentContext!.findRenderObject() as RenderBox;
```

**Comment by ambogatyrev** [comment]
I have some issue((
were you able to fix it?

**Comment by willbryant** [comment]
I think we're using https://pub.dev/packages/slide_to_confirm at the moment.
